apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service }}
spec:
  type: {{ .Values.backend.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.targetPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.repository }}:{{ .Values.backend.imageTag }}"
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.name }}
                  key: ORIGIN
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.name }}
                  key: DATABASE_URL
