---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service }}
spec:
  type: {{ .Values.frontend.type }}
  selector:
    app: {{ .Values.frontend.service }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.service }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.imageTag }}"
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.name }}
                  key: API_URL
