apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  rules:
    - host: {{ .Values.ingress.hosts.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.service }}
                port:
                  number: {{ .Values.frontend.port }}

    - host: {{ .Values.ingress.hosts.backendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.service }}
                port:
                  number: {{ .Values.backend.port }}
