---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.targetPort }}
  clusterIP: {{ .Values.database.clusterIP }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.database.repository }}
          ports:
            - containerPort: {{ .Values.database.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.database.dbName }}
          volumeMounts:
            - name: postgres-storage
              mountPath: {{ .Values.database.mountPath }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaims.name }}
