apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.dbSecret.POSTGRES_USER }} # base64 for "admin"
  POSTGRES_PASSWORD: {{ .Values.secrets.dbSecret.POSTGRES_PASSWORD }} # base64 for "pass"
