apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  ORIGIN: "http://todo.example.com"
  DATABASE_URL: "postgresql://admin:pass@postgres-db:5432/todos?schema=public"
  API_URL: "http://todo-api.example.com"
